<?php

/**
 *
 * $Id: helper.php 1.0.0 2012-03-10 09:50:52 Slava Poddubsky $
 * @package	    Weather Module 
 * @subpackage	Weather Module
 * @version     1.0.0
 * @description Module for show weather for Belarus cities from site http://www.meteonova.by/
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Slava Poddubsky
 * @author mail	vicheslav.p@tut.by
 * @website		  http://berezinogkh.by
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 * The module methods
 * -------------------------------
 * getItems()
 *
 */
// no direct access
defined('_JEXEC') or die('Restricted access');

/**
 * Example Module Helper
 *
 * @package	Weather Module
 * @subpackage	Weather Module
 * @since 	1.0.0
 * @class       ModWeatherHelper
 */
class ModWeatherHelper {
    
    const DAY_PART_HOUR = 6;

    protected $weatherUrl = "http://www.meteonova.by/xml/%d.xml";
    protected $weatherXml = '';
    protected $weatherData = array();
    protected $errorCode = null;
    protected $params = null;
    
    public function getErrorCode() {
        return $this->errorCode;
    }
    
    public function getParams() {
        return $this->params;
    }

    public function setParams($params) {
        $this->params = $params;
    }

    public function getWeather() {
        if(!$this->loadData()){
            return false;
        }
        return $this->weatherData;
    }
    
    protected function getDayPart(){
        $currectHour = date('h');
        if($currectHour > 21){
            return 21;
        } elseif($currectHour > 15){
            return 15;
        } elseif($currectHour > 9){
            return 9;
        } elseif($currectHour > 3){
            return 3;
        } else {
            return 21;
        }
    }
    
    protected function getCacheKey($dayPart){
        return md5('mod_weather_' . date('d_m_Y') . 
                '_hour_' . $dayPart);
    }
    
    protected function getCache($id){
        if(!$this->params->get('cache_href')){
            return false;
        }
        $file = JPATH_CACHE . DS . 'mod_weather' . DS . $id;
        if(file_exists($file)){
            $data = JFile::read($file);
            return json_decode($data);
        } else {
            return false;
        }
    }
    
    protected function setCache($id, $data){
        if(!$this->params->get('cache_href')){
            return;
        }
        $file = JPATH_CACHE . DS . 'mod_weather' . DS . $id;
        $buffer = json_encode($data);
        JFile::write($file, $buffer);
    }
    
    protected function cleanCache(){
        if(!$this->params->get('cache_href')){
            return;
        }
        jimport('joomla.filesystem.folder');
        $folder = JPATH_CACHE . DS . 'mod_weather';
        JFolder::delete($folder);
    }

    protected function loadData() {
        if (!function_exists('simplexml_load_string')) {
            $this->errorCode = 'SIMPLE_XML_NOT_INSTALLED';
            return false;
        }
        $cacheKey = $this->getCacheKey($this->getDayPart());
        if(!$weatherData = $this->getCache($cacheKey)){
            $this->cleanCache();
            $cityId = (int) $this->params->get('city_id');
            if ($cityId == 0) {
                $this->errorCode = 'NO_CITY_ID';
                return false;
            }
            $rederedUrl = sprintf($this->weatherUrl, $cityId);
            $xmlCode = file_get_contents($rederedUrl);
            $this->weatherXml = simplexml_load_string($xmlCode);
            $weatherData = $this->parseWeather();
            $this->setCache($cacheKey, $weatherData);
        }
        $this->weatherData = $weatherData;
        return true;
    }
    
    protected function getWeatherInWord($cloudiness, $precipitation){
        if($cloudiness <= 3 && $precipitation == 4){
            //precipitation = 4 - little rain
            return 'l-rain';
        } elseif($cloudiness <= 3 && $precipitation == 10){
            // precipitation = 10 - no rain
            return 'l-cloudly';
        } elseif($cloudiness <= 3 && $precipitation == 6){
            // precipitation = 6 - precipitation
            return 'precipitation';
        }
    }
    
    protected function parseWeather(){
        $weatherData = array();
        foreach($this->weatherXml->REPORT->TOWN->FORECAST as $forecast){
            $weatherItem = new stdClass();
            $hour = (string)$forecast['hour'];
            $month = (string)$forecast['month'];
            $day = (string)$forecast['day'];
            $year = (string)$forecast['year'];
            $weatherItem->datetime = mktime($hour, 0, 0, $month, $day, $year);
            switch($hour){
                case '3': $weatherItem->dayperiod = 'NIGHT'; 
                    $weatherItem->daypart = 'night';
                    break;
                case '9': $weatherItem->dayperiod = 'MORNING';    
                    $weatherItem->daypart = 'day';
                    break;
                case '15': $weatherItem->dayperiod = 'AFTERNOON';
                    $weatherItem->daypart = 'day';
                    break;
                case '21': $weatherItem->dayperiod = 'EVENING';   
                    $weatherItem->daypart = 'night';
                    break;
            }
            
            $weatherItem->temperature = new stdClass();
            $weatherItem->temperature->min = 
                    (string)$forecast->TEMPERATURE['min'];
            if($weatherItem->temperature->min > 0){
                $weatherItem->temperature->min = '+' . $weatherItem->temperature->min;
            }
            $weatherItem->temperature->max = 
                    (string)$forecast->TEMPERATURE['max'];
            if($weatherItem->temperature->max > 0){
                $weatherItem->temperature->max = '+' . $weatherItem->temperature->max;
            }
            
            $weatherItem->phenomena = new stdClass();
            $weatherItem->phenomena->cloudiness = 
                    (string)$forecast->PHENOMENA['cloudiness'];
            $weatherItem->phenomena->precipitation = 
                    (string)$forecast->PHENOMENA['precipitation'];
            $weatherItem->weatherword = $this->getWeatherInWord($weatherItem->phenomena->cloudiness,
                    $weatherItem->phenomena->precipitation);
            $weatherData[] = $weatherItem;
        }
        return $weatherData;
    }
}

?>