<?php
/**
 *
 * $Id: default.php 1.0.0 2012-03-10 09:50:52 Slava Poddubsky $
 * @package	    Weather Module 
 * @subpackage	Weather Module
 * @version     1.0.0
 * @description Module for show weather for Belarus cities from site http://www.meteonova.by/
 * @copyright	  Copyright © 2012 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Slava Poddubsky
 * @author mail	vicheslav.p@tut.by
 * @website		  http://berezinogkh.by
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 */
// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<div class="module <?= $params->get('moduleclass_sfx') ?>">
    <?php if($module->showtitle): ?>
        <h3><?= $module->title ?></h3>
    <?php endif; ?>

    <div class="content">
        <?php foreach($weatherData as $weatherItem) : ?>
            <p>
                <?= JText::_('AG_CG_' . $weatherItem->dayperiod) ?>
                <?= date("d", $weatherItem->datetime).JText::_('AG_CG_DATE_SUFFIX') ?>
                
            </p>
        <?php endforeach; ?>
    </div>
</div>